services:
  db:
    container_name: 'ecommaster-db'
    env_file:
      - .env
    image: postgres:16.3
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
  # product-service:
  #   build:
  #     context: ./product-service
  #     dockerfile: Dockerfile
  #   container_name: 'EcomMaster-product-service'
  #   depends_on:
  #     - 'db'
  #   env_file:
  #     - ./product-service/.env
  #   ports:
  #     - '8001:8001'
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: 'EcomMaster-user-service'
    depends_on:
      - 'db'
    env_file:
      - ./user-service/.env
    ports:
      - '8000:8000'
version: '3.8'
