services:
  db:
    container_name: 'ecommaster-db'
    env_file:
      - .env
    image: postgres:16.3
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
  user-service:
    build:
      context: ./EcomMaster-user-service
      dockerfile: Dockerfile
    container_name: 'EcomMaster-user-service'
    depends_on:
      - 'db'
    env_file:
      - ./EcomMaster-user-service/.env
    ports:
      - '8000:8000'

version: '3'
