version: '3'

services:
  db:
    image: postgres:16.3
    container_name: 'ecommaster-db'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
